name: Deploy to test
on: [pull_request]
jobs:
  Deploy-Asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12
        with:
          separator: ","
      - name: Power BI Pipeline Deploy #the following are being passed to Power-BI-Pipeline-Deploy
        uses: nathangiusti/Power-BI-Pipeline-Deploy@v2.3
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          source-stage-order: 0  
          tenant_id: "cef04b19-7776-4a94-b89b-375c77a8f936",
          update-app-in-targetWorkspace:  True,
          allow-purgeData:  False      


          
        env:
          CLIENT_ID: ${{ secrets.NON_PROD_SPN_ID }}
          CLIENT_SECRET: ${{ secrets.NON_PROD_SPN_SECRET }}